### ISSUE TITLE
PlaybackDemo should come up with audible song sample

### ISSUE THREAD

**Issue by atsushieno** [Tracktion/tracktion_engine#4]
I'm trying PlaybackDemo so that I can understand how to use this library (I'm absolutely loving it now), and found that none of the songs I have created with Waveform9 are not audible which mostly make use of Collective in the MIDI clips. What are supposed to play just like we can on Waveform? It needs either sample files that are known to play without problem, more setup code in the demo itself, or documentation on what kind of files should work fine.

**Comment by drowaudio** [comment]
Yes, this won't play back Waveform projects directly for two main reasons.
Firstly, we don't currently have a way to scan for plugins in the `PlaybackDemo`, this was done to keep the demo simple and only introduce the core concepts. We may however add this soon.

The second thing is that if you create a session in Waveform, audio files will have been added via Project item references, for the Engine, we're advocating using relative file paths. It's much simpler to get up and running this way.

Eventually, we'll add a way to convert between a Project-based Edit and relative paths but we're not quite there yet. You could do this manually by changing the `source="1234"` `AUDIOCLIP` properties  paths relative to the Edit file.

**Comment by atsushieno** [comment]
Thanks, that helps understanding what it is. I don't see any audio files in my MIDI-clip-only song (never heard of anything about creating a session, it's also not documented on the manual[*1]) but I understand that it is not for PlaybackDemo. Then the next question is, is it even possible with this current tracktion_engine to play a song in a project whose MIDI clips depend on plugins e.g. Collective?

[*1] ![screenshot from 2018-11-19 09-52-26](https://user-images.githubusercontent.com/53929/48699218-dabfba80-ebe0-11e8-890a-272c212471aa.png)

**Comment by drowaudio** [comment]
I've just addressed this with this update: https://github.com/Tracktion/tracktion_engine/commit/f1380028d67b9545b1e587ed58470839e2704489

You can now open the app, and perform a plugin scan. Restart the app to re-load the Edit and it should play back. Unfortunately, because the VST2 SDK isn't open source you won't be able to load VST plugins. It should work with AU and/or VST3 plugins though.

Sorry, by "session" above I meant "Edit".

**Comment by teotigraphix** [comment]
@drowaudio Is the free T7 DAW project files compatible? 

I guess the question, is Waveform and T7 using the same engine code base forward?

**Comment by atsushieno** [comment]
> You can now open the app, and perform a plugin scan. 

Thanks, but this does not seem to be implemented. The Options button on the new plugin list form does not contain "Scan" button.

![screenshot from 2018-11-19 15-40-35](https://user-images.githubusercontent.com/53929/48717606-ae706200-ec11-11e8-84ee-d3a6cc38846b.png)

I'm still unsure about audio files that "will have been added via Project item references". Here is what I have for my example Waveform9 project data. There are only `.traction` and `.tractionedit` files. Should there be other "audio" files than those files?

![screenshot from 2018-11-19 15-49-23](https://user-images.githubusercontent.com/53929/48718202-d2807300-ec12-11e8-8bb6-d0a900dde048.png)

**Comment by FigBug** [comment]
> @drowaudio Is the free T7 DAW project files compatible?
>
> I guess the question, is Waveform and T7 using the same engine code base forward?

Waveform 10 and forward will be using the same codebase as the Open Source engine.

**Comment by FigBug** [comment]
> > You can now open the app, and perform a plugin scan.
> 
> Thanks, but this does not seem to be implemented. The Options button on the new plugin list form does not contain "Scan" button.

Linux only supports VST2 and LADSPA plugins. JUCE can no longer distribute the VST2 headers. If you have a copy of these headers you can add them to your path and enable VST2 or you can add JUCE_PLUGINHOST_LADSPA=1 to the PIP file. However you will still have issues importing W9 edits.

**Comment by atsushieno** [comment]
After checking with @drowaudio at ADC2018 we figured that it is because JUCE does not support VST3 on Linux.
